#! /bin/bash

OEROOT="`pwd`"
OE_CORE_SCRIPTS="`pwd`/layers/openembedded-core/scripts"
BITBAKE_SCRIPTS="`pwd`/bitbake/bin"

# Change PATH to make things more convenient.
export PATH="${OE_CORE_SCRIPTS}":"${BITBAKE_SCRIPTS}":"${PATH}"

# Allow to build for different MACHINE directly.
export BB_ENV_EXTRAWHITE="MACHINE DISTRO"

MANIFEST=".repo/manifests"

# Default MACHINE.
__DEFAULT_MACHINE="qemux86-64"
__DEFAULT_DISTRO=""
cat > conf/auto.conf <<EOF
MACHINE ?= "${__DEFAULT_MACHINE}"
DISTRO ?= "${__DEFAULT_DISTRO}"
EOF

# Config depending on host build machine.
cat > conf/site.conf <<_EOF
SCONF_VERSION = "1"

# Where to store sources
DL_DIR = "${OEROOT}/downloads"

# Where to save shared state
SSTATE_DIR = "${OEROOT}/sstate-cache"

# Which files do we want to parse:
BBFILES ?= "${OEROOT}/layers/openembedded-core/meta/recipes-*/*/*.bb"
_EOF
